# Generated by Django 2.1 on 2018-08-27 02:02

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='名称')),
                ('icon', models.CharField(max_length=20, verbose_name='图片样式')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=app.models.upload_thumb, verbose_name='主图')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='数量')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未确认'), (1, '确认'), (2, '已取消'), (3, '无效'), (4, '退货')], verbose_name='订单状态')),
                ('pay_status', models.SmallIntegerField(choices=[(0, '未付款'), (1, '付款中'), (2, '已付款')], verbose_name='支付状态')),
                ('shipping_status', models.SmallIntegerField(choices=[(0, '未发货'), (1, '已发货'), (2, '已收货'), (3, '退货 ')], verbose_name='配送状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=6, message='用户名不能少于6位')], verbose_name='用户名')),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='密码不能少于8位')], verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='2323', max_length=100, verbose_name='地址')),
                ('phone', models.CharField(default='123123123', max_length=11, verbose_name='电话')),
                ('recipient', models.CharField(default='123123123', max_length=10, verbose_name='收件人')),
                ('postcode', models.CharField(default='123123', max_length=6, verbose_name='邮编')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OrderInfo', verbose_name='订单ID'),
        ),
        migrations.AddField(
            model_name='cartgoods',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ManyToManyField(through='app.CartGoods', to='app.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
