# Generated by Django 2.1 on 2018-08-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='xiaoji',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='小计'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='zongjia',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='总价'),
            preserve_default=False,
        ),
    ]
