# Generated by Django 2.1 on 2018-08-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180828_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='xiaoji',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='zongjia',
        ),
    ]
